# Generated by Django 5.0.2 on 2024-02-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Details',
            new_name='Contact_Detail',
        ),
    ]
