# Generated by Django 5.0.2 on 2024-02-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_main_title', models.TextField()),
                ('outlet_name', models.TextField()),
                ('address_line_1', models.TextField()),
                ('address_line_2', models.TextField()),
                ('address_line_3', models.TextField()),
                ('address_line_4', models.TextField(null=True)),
                ('address_line_5', models.TextField(null=True)),
                ('outlet_landline', models.IntegerField(null=True)),
                ('outlet_email', models.TextField(null=True)),
            ],
        ),
    ]
