# Generated by Django 5.0.2 on 2024-02-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='address_line_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='address_line_2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='address_line_3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='address_line_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='address_line_5',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='outlet_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='outlet_main_title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='outlet_name',
            field=models.CharField(max_length=50),
        ),
    ]
