# Generated by Django 5.0.2 on 2024-02-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_outlet_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='address_line_5',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
