# Generated by Django 5.0.2 on 2024-02-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_outlet_address_line_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='outlet_landline',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
