# Generated by Django 5.0.2 on 2024-02-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_outlet_address_line_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='outlet_landline',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
