# Generated by Django 5.0.2 on 2024-02-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_outlet_outlet_landline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='address_line_1',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='address_line_2',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='address_line_3',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='address_line_4',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='address_line_5',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
