# Generated by Django 5.0.2 on 2024-02-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_outlet_address_line_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_image', models.ImageField(upload_to='team')),
                ('Member_name', models.CharField(max_length=50)),
                ('Member_title', models.CharField(max_length=50)),
            ],
        ),
    ]
